suppressMessages(library(CompQuadForm)); options(digits=4)
set.seed(3); n<-400; x<-runif(n,-2.5,2.5); y<-rbinom(n,1,1-exp(-exp(0.7*x)))   # true cloglog, fit logit
fit<-glm(y~x,family=binomial()); ph<-as.numeric(fitted(fit))
G<-5; grp<-pmin(ceiling(rank(ph,ties.method="first")/(n/G)),G); idx<-split(seq_len(n),grp)
ng<-sapply(idx,length); og<-sapply(idx,function(I)sum(y[I])); eg<-sapply(idx,function(I)sum(ph[I]))
Wii<-ph*(1-ph); Vg<-sapply(idx,function(I)sum(Wii[I])); pbar<-sapply(idx,function(I)mean(ph[I]))
r<-(og-eg)/sqrt(Vg)
cat("=== per-group table (G=5) ===\n")
print(round(data.frame(group=1:G,n_g=ng,o_g=og,e_g=eg,V_g=Vg,pibar=pbar,r_g=r),3))
cat("\n(1-2*pibar) [Farrington contrast direction]:\n"); print(round(1-2*pbar,3))
Z<-as.matrix(poly(pbar,2)); colnames(Z)<-c("P1","P2")
cat("\n=== basis Z (orthogonal poly deg 2) ===\n"); print(round(Z,3))
Pz<-Z%*%solve(crossprod(Z))%*%t(Z); S<-as.numeric(t(r)%*%Pz%*%r)
cat(sprintf("\nS = r' Pz r = %.4f\n",S))
X<-model.matrix(fit); U<-t(sapply(idx,function(I)colSums(Wii[I]*X[I,,drop=FALSE])))/sqrt(Vg)
Om<-diag(G)-U%*%solve(crossprod(X,Wii*X))%*%t(U)
cat("\n=== Omega = I - U(X'WX)^{-1}U' (5x5) ===\n"); print(round(Om,3))
cat("\ndiag(Omega):\n"); print(round(diag(Om),3))
M<-solve(crossprod(Z))%*%(t(Z)%*%Om%*%Z); lam<-Re(eigen(M,only.values=TRUE)$values); lam<-lam[lam>1e-9]
cat("\nlambda (eigenvalues of (Z'Z)^{-1}Z'OmZ):\n"); print(round(lam,4))
cc<-sum(lam^2)/sum(lam); nu<-sum(lam)^2/sum(lam^2); p_satt<-1-pchisq(S/cc,nu)
p_imhof<-CompQuadForm::imhof(S,lam)$Qq
naive<-1-pchisq(S,length(lam))
cat(sprintf("\nSatterthwaite: c=%.4f, nu=%.4f, p=%.4f\n",cc,nu,p_satt))
cat(sprintf("Imhof p = %.4f\n",p_imhof))
cat(sprintf("Naive chi^2_2 p (ignoring Omega) = %.4f  [too conservative]\n",naive))
