## emit_tables_A.R -- write the two new SiM tables straight from runA, so no number is retyped.
## ---- archive paths (inserted by make_archive.py; the convention is in README.md, "How to run") -------------
EDGE_ARCHIVE_ROOT <- local({
  r <- Sys.getenv("EDGE_ARCHIVE_ROOT")
  if (!nzchar(r)) {
    f <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE))
    r <- if (length(f)) file.path(dirname(normalizePath(f[1], winslash = "/")), "..", "..") else getwd()
  }
  r <- normalizePath(r, winslash = "/", mustWork = FALSE)
  Sys.setenv(EDGE_ARCHIVE_ROOT = r)        # so worker processes started from here resolve the same root
  r
})
edge_path <- function(...) file.path(EDGE_ARCHIVE_ROOT, ...)
edge_battery <- function(...) {           # the author's battery/ folder: analysis/ -> results/analysis, rest -> results/blocks
  if (...length() == 0L) return(edge_path("results", "blocks"))
  p <- file.path(...)
  ifelse(p == "analysis" | startsWith(p, "analysis/"), edge_path("results", p), edge_path("results", "blocks", p))
}
edge_out <- function(...) { d <- edge_path("output", ...); dir.create(d, showWarnings = FALSE, recursive = TRUE); d }
## ---------------------------------------------------------------------------------------------------------------
S <- read.csv("runA_pstar_giviti_summary.csv", stringsAsFactors = FALSE)
OUT <- edge_out("submission_statistics_in_medicine")

LAB <- c(EDGE.poly2 = "\\DEFp{2}", EDGE.poly3 = "\\DEFp{3}", EDGE.stk = "\\DEFstk{}",
         HL_F = "\\EFname{}", HL = "\\HLname{}", HL_w = "\\HLname{}$_w$",
         Stukel = "Stukel", GiViTI = "GiViTI")
ORD <- c("EDGE.poly3", "EDGE.poly2", "EDGE.stk", "Stukel", "GiViTI", "HL_F", "HL", "HL_w")
f3 <- function(x) ifelse(is.na(x), "---", sprintf("%.3f", x))

## ---------- Table: size and power against p*, at G = 10 ----------
G0 <- 10
z <- S[S$G == G0, ]
lines <- c(
  "% AUTO-GENERATED by simulations/emit_tables_A.R -- do not hand-edit; re-run the script.",
  "\\begin{table}[htbp]\\centering\\small",
  paste0("\\caption{Realised size and size-adjusted power as the number of estimated coefficients ",
         "$p^{*}$ grows, at $n=1000$ and $G=", G0, "$. The departure is held fixed and the added ",
         "covariates are pure noise with true coefficient zero, so every change down a row is the ",
         "effect of $p^{*}$ alone. Nominal size $0.05$; Monte Carlo standard error $0.005$ on size ",
         "and at most $0.011$ on power ($B=2000$). At $p^{*}=20$ the fitting correction removes a ",
         "rank-$20$ subspace from a $", G0, "$-dimensional residual space.}"),
  "\\label{tab:pstar}",
  "\\begin{tabular}{l cccc c cccc}",
  "\\toprule",
  "& \\multicolumn{4}{c}{Size (null)} && \\multicolumn{4}{c}{Size-adjusted power (cloglog)}\\\\",
  "\\cmidrule(lr){2-5}\\cmidrule(lr){7-10}",
  "Test & $p^{*}{=}3$ & $5$ & $10$ & $20$ && $p^{*}{=}3$ & $5$ & $10$ & $20$\\\\",
  "\\midrule")
for (t in ORD) {
  sz <- sapply(c(3, 5, 10, 20), function(p) z$size_raw[z$test == t & z$pstar == p & z$scenario == "cloglog"][1])
  pw <- sapply(c(3, 5, 10, 20), function(p) z$power_adj[z$test == t & z$pstar == p & z$scenario == "cloglog"][1])
  lines <- c(lines, paste0(LAB[[t]], " & ", paste(f3(sz), collapse = " & "), " && ",
                           paste(f3(pw), collapse = " & "), "\\\\"))
}
lines <- c(lines, "\\bottomrule", "\\end{tabular}", "\\end{table}")
writeLines(lines, file.path(OUT, "tab_pstar.tex"))
cat("wrote tab_pstar.tex\n")

## ---------- Table: GiViTI head-to-head ----------
lines <- c(
  "% AUTO-GENERATED by simulations/emit_tables_A.R -- do not hand-edit; re-run the script.",
  "\\begin{table}[htbp]\\centering\\small",
  paste0("\\caption{The GiViTI calibration test \\citep{nattino2015new} against the directed ",
         "bases and the partition family, on identical samples at $n=1000$, $p^{*}=3$. Size-adjusted ",
         "power; realised size in parentheses. GiViTI is not a partition test: it fits a polynomial ",
         "to the calibration curve with a data-driven degree, so it is entered here as an ",
         "out-of-family reference rather than as a member of the comparison set. Monte Carlo ",
         "standard error at most $0.011$ ($B=2000$). \\emph{GiViTI leads on the link departure at ",
         "both group counts.}}"),
  "\\label{tab:giviti}",
  "\\begin{tabular}{l cc c cc}",
  "\\toprule",
  "& \\multicolumn{2}{c}{cloglog link} && \\multicolumn{2}{c}{omitted interaction}\\\\",
  "\\cmidrule(lr){2-3}\\cmidrule(lr){5-6}",
  "Test & $G{=}10$ & $G{=}20$ && $G{=}10$ & $G{=}20$\\\\",
  "\\midrule")
for (t in ORD) {
  g <- function(sc, G) {
    r <- S[S$test == t & S$scenario == sc & S$G == G & S$pstar == 3, ]
    if (!nrow(r)) return("---")
    sprintf("%.3f (%.3f)", r$power_adj[1], r$size_raw[1])
  }
  lines <- c(lines, paste0(LAB[[t]], " & ", g("cloglog", 10), " & ", g("cloglog", 20),
                           " && ", g("binint", 10), " & ", g("binint", 20), "\\\\"))
}
lines <- c(lines, "\\bottomrule", "\\end{tabular}", "\\end{table}")
writeLines(lines, file.path(OUT, "tab_giviti.tex"))
cat("wrote tab_giviti.tex\n")

## ---------- the numbers the prose must quote ----------
cat("\n--- numbers for the prose ---\n")
e <- S[S$test == "EDGE.poly3" & S$scenario == "cloglog" & S$G == 10, ]
cat(sprintf("EDGE3 cloglog G=10 power: p*=3 %.3f -> p*=20 %.3f  (drop %.3f, %.0f%% relative)\n",
    e$power_adj[e$pstar == 3], e$power_adj[e$pstar == 20],
    e$power_adj[e$pstar == 3] - e$power_adj[e$pstar == 20],
    100 * (1 - e$power_adj[e$pstar == 20] / e$power_adj[e$pstar == 3])))
h <- S[S$test == "HL" & S$scenario == "cloglog" & S$G == 10, ]
cat(sprintf("HL    cloglog G=10 power: p*=3 %.3f -> p*=20 %.3f  (drop %.3f, %.0f%% relative)\n",
    h$power_adj[h$pstar == 3], h$power_adj[h$pstar == 20],
    h$power_adj[h$pstar == 3] - h$power_adj[h$pstar == 20],
    100 * (1 - h$power_adj[h$pstar == 20] / h$power_adj[h$pstar == 3])))
sz <- S[S$scenario == "cloglog" & S$test %in% ORD, ]
cat(sprintf("size range over ALL tests, p* and G: %.4f to %.4f (nominal 0.05, MCSE 0.0049)\n",
    min(sz$size_raw), max(sz$size_raw)))
edg <- sz[grepl("EDGE", sz$test), ]
cat(sprintf("size range for the EDGE bases only:  %.4f to %.4f  -> max %.1f MCSE from nominal\n",
    min(edg$size_raw), max(edg$size_raw), max(abs(edg$size_raw - .05)) / 0.00487))
st <- S[S$test == "Stukel" & S$scenario == "cloglog", ]
es <- S[S$test == "EDGE.stk" & S$scenario == "cloglog", ]
cat(sprintf("decline rate: Stukel %.1f%%-%.1f%%  vs EDGE-stk %.2f%%-%.2f%%\n",
    100 * min(st$na_alt), 100 * max(st$na_alt), 100 * min(es$na_alt), 100 * max(es$na_alt)))
