## emit_tables_K2.R -- the link-family (Aranda-Ordaz) basis table for the SiM paper, straight from
## runK2_ao_basis_summary.csv so no number is retyped. Companion of emit_tables_FGHI.R.
## ---- archive paths (inserted by make_archive.py; the convention is in README.md, "How to run") -------------
EDGE_ARCHIVE_ROOT <- local({
  r <- Sys.getenv("EDGE_ARCHIVE_ROOT")
  if (!nzchar(r)) {
    f <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE))
    r <- if (length(f)) file.path(dirname(normalizePath(f[1], winslash = "/")), "..", "..") else getwd()
  }
  r <- normalizePath(r, winslash = "/", mustWork = FALSE)
  Sys.setenv(EDGE_ARCHIVE_ROOT = r)        # so worker processes started from here resolve the same root
  r
})
edge_path <- function(...) file.path(EDGE_ARCHIVE_ROOT, ...)
edge_battery <- function(...) {           # the author's battery/ folder: analysis/ -> results/analysis, rest -> results/blocks
  if (...length() == 0L) return(edge_path("results", "blocks"))
  p <- file.path(...)
  ifelse(p == "analysis" | startsWith(p, "analysis/"), edge_path("results", p), edge_path("results", "blocks", p))
}
edge_out <- function(...) { d <- edge_path("output", ...); dir.create(d, showWarnings = FALSE, recursive = TRUE); d }
## ---------------------------------------------------------------------------------------------------------------
OUT <- edge_out("submission_statistics_in_medicine")
S <- read.csv("runK2_ao_basis_summary.csv", stringsAsFactors = FALSE)
LAB <- c(EDGE.poly3 = "\\DEFp{3} (default)", EDGE.stk = "\\DEFstk{}", EDGE.ao = "\\DEFao{}",
         Stukel = "Stukel (refit)", GiViTI = "GiViTI", HL = "\\HLname{}")
ORD <- c("EDGE.poly3", "EDGE.stk", "EDGE.ao", "Stukel", "GiViTI", "HL")
COLS <- list(c("cloglog", 500), c("cloglog", 1000), c("loglog", 1000), c("probit", 5000), c("binint", 1000), c("osc4", 1000))
cell <- function(t, sc, n) { r <- S[S$test == t & S$scen == sc & S$n == n, ]; if (!nrow(r)) "---" else sprintf("%.3f", r$power_adj[1]) }
edge_sizes <- S$size[grepl("EDGE", S$test)]
lines <- c("% AUTO-GENERATED by simulations/emit_tables_K2.R -- do not hand-edit; re-run the script.",
  "\\begin{table}[htbp]\\centering\\small",
  sprintf(paste0("\\caption{A basis aimed at one link family. Size-adjusted power of the one-column ",
    "Aranda--Ordaz basis \\DEFao{} beside the default, the Stukel basis and the two non-partition ",
    "references, at $G=n/25$, $B=2000$ (Monte Carlo standard error at most $0.011$; realised sizes ",
    "of the EDGE bases $%.3f$ to $%.3f$). The complementary log--log link is the family the basis ",
    "is built from; the log--log link is its mirror image; the other three columns are departures ",
    "of a different kind. Differences below $0.014$ are ties.}"), min(edge_sizes), max(edge_sizes)),
  "\\label{tab:ao}",
  "\\begin{tabular}{l cc c c c c}", "\\toprule",
  "& \\multicolumn{2}{c}{cloglog} & log--log & probit & interaction & oscillation \\\\",
  "\\cmidrule(lr){2-3}",
  "Test & $n{=}500$ & $n{=}1000$ & $n{=}1000$ & $n{=}5000$ & $n{=}1000$ & $n{=}1000$ \\\\", "\\midrule")
for (t in ORD) lines <- c(lines, paste0(LAB[[t]], " & ", paste(sapply(COLS, function(cn) cell(t, cn[1], as.numeric(cn[2]))), collapse = " & "), " \\\\"))
lines <- c(lines, "\\bottomrule", "\\end{tabular}", "\\end{table}")
writeLines(lines, file.path(OUT, "tab_ao.tex")); cat("wrote tab_ao.tex\n")
for (cn in COLS) cat(sprintf("%-8s n=%5d: poly3 %s | ao %s | Stukel %s | GiViTI %s\n", cn[1], as.numeric(cn[2]),
  cell("EDGE.poly3", cn[1], as.numeric(cn[2])), cell("EDGE.ao", cn[1], as.numeric(cn[2])), cell("Stukel", cn[1], as.numeric(cn[2])), cell("GiViTI", cn[1], as.numeric(cn[2]))))
