## emit_tables_FGHI.R -- write the SiM tables for the group-count rule (run F + run G), the
## external-validation mode (run H) and the Diabetes-130 demonstration (run I) straight from the
## result files, so no number is retyped. Companion of emit_tables_A.R.
## ---- archive paths (inserted by make_archive.py; the convention is in README.md, "How to run") -------------
EDGE_ARCHIVE_ROOT <- local({
  r <- Sys.getenv("EDGE_ARCHIVE_ROOT")
  if (!nzchar(r)) {
    f <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE))
    r <- if (length(f)) file.path(dirname(normalizePath(f[1], winslash = "/")), "..", "..") else getwd()
  }
  r <- normalizePath(r, winslash = "/", mustWork = FALSE)
  Sys.setenv(EDGE_ARCHIVE_ROOT = r)        # so worker processes started from here resolve the same root
  r
})
edge_path <- function(...) file.path(EDGE_ARCHIVE_ROOT, ...)
edge_battery <- function(...) {           # the author's battery/ folder: analysis/ -> results/analysis, rest -> results/blocks
  if (...length() == 0L) return(edge_path("results", "blocks"))
  p <- file.path(...)
  ifelse(p == "analysis" | startsWith(p, "analysis/"), edge_path("results", p), edge_path("results", "blocks", p))
}
edge_out <- function(...) { d <- edge_path("output", ...); dir.create(d, showWarnings = FALSE, recursive = TRUE); d }
## ---------------------------------------------------------------------------------------------------------------
OUT <- edge_out("submission_statistics_in_medicine")
LAB <- c(EDGE.poly2 = "\\DEFp{2}", EDGE.poly3 = "\\DEFp{3}", EDGE.stk = "\\DEFstk{}",
         HL_F = "\\EFname{}", HL = "\\HLname{}", HL_w = "\\HLname{}$_w$",
         Stukel = "Stukel", GiViTI = "GiViTI")
f3 <- function(x) ifelse(is.na(x), "---", sprintf("%.3f", x))
hdr <- "% AUTO-GENERATED by simulations/emit_tables_FGHI.R -- do not hand-edit; re-run the script."

## ================= Table: the group-count rule (run F), cloglog and probit =================
F <- read.csv("runF_grule_summary.csv", stringsAsFactors = FALSE)
F$m_actual <- round(F$n / F$G)
## n = 20000 is capped at G = 400 (m = 50); the three "m = 15/25/50" rows there are one cell run
## three times. Keep one copy, labelled by its true m.
F <- F[!(F$n == 20000 & F$m %in% c(15, 25)), ]
F$m <- F$m_actual
ORD <- c("EDGE.poly3", "EDGE.stk", "Stukel", "GiViTI", "HL_F", "HL")
MS  <- c(15, 25, 50, 100, 200)
cell <- function(sc, nn, t, m) { r <- F[F$scen == sc & F$n == nn & F$test == t & F$m == m, ]
  if (!nrow(r)) "---" else sprintf("%.3f", r$power_adj[1]) }
sz <- function(nn, t) { r <- F[F$n == nn & F$test == t & F$scen == "cloglog", ]
  sprintf("%.3f--%.3f", min(r$size), max(r$size)) }
lines <- c(hdr,
  "\\begin{table}[htbp]\\centering\\small",
  paste0("\\caption{Size-adjusted power against the number of observations per risk group, ",
         "$m=n/G$, for the complementary log--log bow at $n=1000$ and the probit S at $n=5000$ ",
         "($B=2000$; Monte Carlo standard error at most $0.011$). A smaller $m$ is a finer partition. ",
         "The last column is the range of realised null size of each test over the five partitions ",
         "at $n=1000$ (nominal $0.05$). Stukel's test and GiViTI do not partition, so their row is ",
         "one value repeated; they are the non-partition references. The directed tests gain from a ",
         "finer partition and the omnibus tests lose, down to their nominal level; the theory of ",
         "Section~\\ref{sec:growingG} says why.}"),
  "\\label{tab:grule}",
  "\\begin{tabular}{l ccccc c ccccc c}",
  "\\toprule",
  "& \\multicolumn{5}{c}{cloglog bow, $n=1000$} && \\multicolumn{5}{c}{probit S, $n=5000$} & \\\\",
  "\\cmidrule(lr){2-6}\\cmidrule(lr){8-12}",
  paste0("Test & ", paste(sprintf("$m{=}%d$", MS), collapse = " & "), " && ",
         paste(sprintf("$%d$", MS), collapse = " & "), " & size range \\\\"),
  "\\midrule")
for (t in ORD) lines <- c(lines, paste0(LAB[[t]], " & ",
  paste(sapply(MS, function(m) cell("cloglog", 1000, t, m)), collapse = " & "), " && ",
  paste(sapply(MS, function(m) cell("probit", 5000, t, m)), collapse = " & "), " & ",
  sz(1000, t), " \\\\"))
lines <- c(lines, "\\bottomrule", "\\end{tabular}", "\\end{table}")
writeLines(lines, file.path(OUT, "tab_grule.tex")); cat("wrote tab_grule.tex\n")

## ================= Table: external-validation mode (run H) =================
H <- read.csv("runH_overconfidence_summary.csv", stringsAsFactors = FALSE)
HT <- c("EDGE.stk4", "EDGE.poly4", "EDGE.slope2", "SlopeLRT", "GiViTI.ext", "HL.ext")
HLAB <- c(EDGE.stk4 = "\\DEFstk{} ($k=4$)", EDGE.poly4 = "\\DEFp{3} ($k=4$)",
          EDGE.slope2 = "EDGE slope ($k=2$)", SlopeLRT = "Cox--Miller slope LRT",
          GiViTI.ext = "GiViTI (external)", HL.ext = "\\HLname{} ($\\chi^2_G$)")
KINDS <- c(temp = "temp.", asym_hi = "upper tail", asym_lo = "lower tail",
           probit_comp = "probit")
hc <- function(k, t, nn, s = 0.85) { r <- H[H$kind == k & H$test == t & H$n == nn & H$s == s, ]
  if (!nrow(r)) "---" else sprintf("%.3f", r$power_adj[1]) }
hs <- function(t) { r <- H[H$test == t, ]; sprintf("%.3f--%.3f", min(r$size), max(r$size)) }
lines <- c(hdr,
  "\\begin{table}[htbp]\\centering\\small",
  paste0("\\caption{External-validation mode: size-adjusted power against four distortions of a ",
         "frozen prediction (severity $s=0.85$, Section~\\ref{sec:extresults}) at $n=1000$ and ",
         "$n=2000$ validation cases, $G=n/25$, $B=2000$ (Monte Carlo standard error at most ",
         "$0.011$). The last column is the range of realised null size of each test over ",
         "$n\\in\\{500,1000,2000,5000\\}$ (nominal $0.05$). ``EDGE slope'' is the $k=2$ sub-basis ",
         "$[1,\\bar\\eta]$, the grouped form of the calibration intercept-and-slope test. All four ",
         "distortions are close to a pure logit rescaling, which is the slope test's own alternative; ",
         "the table is the honest cost of the two extra shape directions, not a win.}"),
  "\\label{tab:external}",
  "\\begin{tabular}{l cccc c cccc c}",
  "\\toprule",
  "& \\multicolumn{4}{c}{$n=1000$} && \\multicolumn{4}{c}{$n=2000$} & \\\\",
  "\\cmidrule(lr){2-5}\\cmidrule(lr){7-10}",
  paste0("Test & ", paste(KINDS, collapse = " & "), " && ", paste(KINDS, collapse = " & "),
         " & size range \\\\"),
  "\\midrule")
for (t in HT) lines <- c(lines, paste0(HLAB[[t]], " & ",
  paste(sapply(names(KINDS), function(k) hc(k, t, 1000)), collapse = " & "), " && ",
  paste(sapply(names(KINDS), function(k) hc(k, t, 2000)), collapse = " & "), " & ", hs(t), " \\\\"))
lines <- c(lines, "\\bottomrule", "\\end{tabular}", "\\end{table}")
writeLines(lines, file.path(OUT, "tab_external.tex")); cat("wrote tab_external.tex\n")

## ================= Table: Diabetes-130 (run I), development half and validation half =========
Idev <- read.csv("runI_bigdata_dev.csv", stringsAsFactors = FALSE)
Ival <- read.csv("runI_bigdata_val.csv", stringsAsFactors = FALSE)
GS <- c(10, 50, 200, 1000, 2000)
pe <- function(p) { if (is.na(p)) return("---")
  if (p < 1e-4) { e <- floor(log10(p)); sprintf("$10^{%d}$", e) } else sprintf("%.3f", p) }
lines <- c(hdr,
  "\\begin{table}[htbp]\\centering\\small",
  paste0("\\caption{The Diabetes-130 data (readmission within 30 days; $n=101{,}763$, split ",
         "$50/50$ at random). \\emph{Left}: development half ($n=50{,}881$), internal mode, ",
         "$p$-values of the pre-specified default and of the Hosmer--Lemeshow test as the partition ",
         "is refined from $G=10$ to $G=2000$ ($m=25$). \\emph{Right}: validation half ",
         "($n=50{,}882$), external mode on the frozen predictions, the statistic on $k=4$ degrees of ",
         "freedom for the default basis and on $G$ for the Hosmer--Lemeshow sum. The directed ",
         "verdict is the same at every $G$; the omnibus verdict moves from $10^{-11}$ to $0.38$ ",
         "on the same data and the same model. Powers of ten are rounded down.}"),
  "\\label{tab:diabetes}",
  "\\begin{tabular}{r r cc c cc}",
  "\\toprule",
  "& & \\multicolumn{2}{c}{development, internal mode} && \\multicolumn{2}{c}{validation, external mode} \\\\",
  "\\cmidrule(lr){3-4}\\cmidrule(lr){6-7}",
  "$G$ & $m$ & \\DEFp{3} $p$ & \\HLname{} $p$ && \\DEFp{3} $S$ (4 df), $p$ & \\HLname{} $S$ ($G$ df), $p$ \\\\",
  "\\midrule")
for (G in GS) { d <- Idev[Idev$G == G, ]; v <- Ival[Ival$G == G, ]
  lines <- c(lines, sprintf("%d & %d & %s & %s && %.1f, %s & %.0f, %s \\\\", G, d$m,
    pe(d$EDGE.poly3), pe(d$HL), v$poly_stat, pe(v$poly_p), v$hl_stat, pe(v$hl_p))) }
lines <- c(lines, "\\bottomrule", "\\end{tabular}", "\\end{table}")
writeLines(lines, file.path(OUT, "tab_diabetes.tex")); cat("wrote tab_diabetes.tex\n")

## ================= numbers the prose must quote =================
cat("\n--- run F: EDGE-poly3 cloglog n=1000 by m; HL by m ---\n")
print(F[F$scen == "cloglog" & F$n == 1000 & F$test %in% c("EDGE.poly3", "HL"), c("m", "test", "size", "power_adj")])
cat("\n--- run F: probit n=5000 & n=20000 by m ---\n")
print(F[F$scen == "probit" & F$n %in% c(5000, 20000) & F$test %in% c("EDGE.poly3", "EDGE.stk", "Stukel", "GiViTI", "HL"), c("n", "m", "test", "size", "power_adj")])
cat("\n--- run F: size range EDGE bases over everything ---\n")
e <- F[grepl("EDGE", F$test), ]; cat(sprintf("%.3f to %.3f\n", min(e$size), max(e$size)))
cat("\n--- run G: G=10 vs rule, EDGE-poly3, every scenario ---\n")
G <- read.csv("runG_validate_summary.csv", stringsAsFactors = FALSE)
g3 <- G[G$test == "EDGE.poly3", ]
w <- reshape(g3[, c("n", "scen", "arm", "power_adj")], idvar = c("n", "scen"), timevar = "arm", direction = "wide")
print(w)
cat("\n--- run G: size of EDGE bases under the rule ---\n")
gr <- G[G$arm == "rule" & grepl("EDGE", G$test), ]; cat(sprintf("%.3f to %.3f\n", min(gr$size), max(gr$size)))
cat("\n--- run H: size range all tests ---\n"); cat(sprintf("%.3f to %.3f\n", min(H$size), max(H$size)))
cat("\n--- run I: dev slope-LRT and giviti are in runI.log; calibration curve ---\n")
print(read.csv("runI_bigdata_calcurve.csv"))
